config/routes.rb
Rails.application.routes.draw do
  resources :users
  get 'login/new_user'
  post 'login/new_user' => "login#new_user"

  get 'login/login'

  resources :happy_things
  get 'happy_entry/happyentry'

  root 'application#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/happy_thing.rb
class HappyThing < ApplicationRecord
  validates :happy_things,
    presence: true,
    is_disable_char: true
    # validates :user_id, presence: true

end

app/models/user.rb
class User < ApplicationRecord
    validates :password_digest,
      presence: true,
      length:  { minimum: 4,
                too_short: "は4桁以上ご入力ください。",
                maximum: 10,
                too_long: "は10桁以下でご入力ください。" 
                },
      is_disable_char: true
      validate :is_eazy_password
end

def is_eazy_password

  #パスワードが全て同じ文字
  if /^#{self.password_digest[0, 1]}+$/ =~ self.password_digest
    #エラーメッセージを設定
    errors[:base] << "パスワードは異なる文字を組み合わせて設定してください。"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def hello
    render html: "hello, world!"
  end

end

app/controllers/happy_entry_controller.rb
class HappyEntryController < ApplicationController
  def happyentry
  end
end

app/controllers/happy_things_controller.rb
class HappyThingsController < ApplicationController
  before_action :set_happy_thing, only: [:show, :edit, :update, :destroy]

  # GET /happy_things
  # GET /happy_things.json
  def index
    @happy_things = HappyThing.all
  end

  # GET /happy_things/1
  # GET /happy_things/1.json
  def show
  end

  # GET /happy_things/new
  def new
    @happy_thing = HappyThing.new
  end

  # GET /happy_things/1/edit
  def edit
  end

  # POST /happy_things
  # POST /happy_things.json
  def create
    #happy_thingオブジェクト作成
    @happy_thing = HappyThing.new(happy_thing_params)

    respond_to do |format|
      #DB登録し、成功の場合
      if @happy_thing.save
        #htmlのフォーマットを指定し、登録成功ページへ遷移する
        format.html { render :show, status: :created, location: @happy_thing }
      #登録失敗の場合
      else
        #htmlのフォーマットを指定し、new画面へリダイレクトする
        format.html { render :new }
        # format.html { render new: @happy_thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /happy_things/1
  # PATCH/PUT /happy_things/1.json
  def update
    respond_to do |format|
      if @happy_thing.update(happy_thing_params)
        format.html { redirect_to @happy_thing, notice: 'Happy thing was successfully updated.' }
        format.json { render :show, status: :ok, location: @happy_thing }
      else
        format.html { render :edit }
        format.json { render json: @happy_thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /happy_things/1
  # DELETE /happy_things/1.json
  def destroy
    @happy_thing.destroy
    respond_to do |format|
      format.html { redirect_to happy_things_url, notice: 'Happy thing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_happy_thing
      @happy_thing = HappyThing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def happy_thing_params
      params.require(:happy_thing).permit(:happy_things, :user_id)
    end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  
  def new
    # @user = User.new
  end
  
  def new_user
    #userオブジェクト作成
    # @user = User.new(user_params)
    # puts @user

    respond_to do |format|
      
      #DB登録し、成功の場合
      # if @user.save
        #htmlのフォーマットを指定し、登録成功ページへ遷移する
        format.html { render :login, status: :created, location: @user }
      #登録失敗の場合
      # else
        # puts @user
        #htmlのフォーマットを指定し、new画面へリダイレクトする
      #   format.html { render :new_user }
      #   format.html { render new: @user.errors, status: :unprocessable_entity }
      end
    # end
  end

  def login
  end
  
  private
  # Use callbacks to share common setup or constraints between actions.

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    puts @user
    params.require(:user).permit(:user_id, :user_password, :user_password_second)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    
    #ストロングパラメータを取得
    user_params
    
    #passwordの不一致チェック
    unless user_params["password_digest"] === user_params["password_confirmation"]
      
      #userモデルにuser_idのみ設定
      @user = User.new(user_params.select {|k, v| k == "user_id"})
      
      #エラーメッセージを設定
      @user.errors[:base] << "パスワードが異なっています。"
      
      #new画面にエラー遷移する
      respond_to do |format|
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
      return

    end
    
    respond_to do |format|
      #userモデルにuser_idとpassword_digestのハッシュを指定
      @user = User.new(user_params.select {|k, v| k == "user_id" || k == "password_digest"})
    
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        #userモデルのパスワードを消去
        @user.password_digest = ""
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:user_id, :password_digest, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/happy_entry_helper.rb
module HappyEntryHelper
end

app/helpers/happy_things_helper.rb
module HappyThingsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/happy_entry/happyentry.html.erb
<h1>はっぴー貯金</h1>

<p>今日はどんな良いことがありましたか？</p>
<input type="text" name="todaysHappy">
<%= form.text_field :name, id: :user_name %>

app/views/happy_things/_form.html.erb
<%= form_with(model: happy_thing, local: true) do |form| %>
  <!--DB登録エラーがある場合-->
  <% if happy_thing.errors.any? %>
    <div id="error_explanation">
      <h3>入力してください</h3>
      <!--<h2><%= pluralize(happy_thing.errors.count, "error") %> prohibited this happy_thing from being saved:</h2>-->
      <ul>
      <!--エラーメッセージをリスト表示-->
      <% happy_thing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <!--<%= form.label :happy_things %>-->
    <%= form.text_area :happy_things, id: :happy_thing_happy_things %>
  </div>

  <!--<div class="field">-->
  <!--  <%= form.label :user_id %>-->
  <!--  <%= form.number_field :user_id, id: :happy_thing_user_id %>-->
  <!--</div>-->

  <div class="actions">
    <!--<%= form.submit %>-->
    <%= submit_tag "貯金する!" ,name: "entry_button"%>
  </div>
<% end %>

app/views/happy_things/edit.html.erb
<h1>Editing Happy Thing</h1>

<%= render 'form', happy_thing: @happy_thing %>

<%= link_to 'Show', @happy_thing %> |
<%= link_to 'Back', happy_things_path %>

app/views/happy_things/index.html.erb
<%= stylesheet_link_tag "happy_things/index/index", :media => "all" %>

<% content_for :menubar do %>
  <% link_to 'HAPPYを貯金する！', new_happy_thing_path %>
<% end %>

<div class="contents">
  <table class="happyframe">
    <thead>
      <tr>
        <th colspan="2">最近のHAPPY</th>
      </tr>
    </thead>
  
    <tbody>
      <tr>
        <td class="happyframe">
          <table class="happycontents">
            <% @happy_things.each do |happy_thing| %>
              <tr>
                <td>
                  <p class="happythings"><%= happy_thing.happy_things %></p>
                  <p class="entrydate"><%= happy_thing.created_at %></p>
                  <div class="border"></div>
                </td>
              </tr>
            <% end %>
          </table>
        </td>
       </tr>
    </tbody>
  </table>
</div>

app/views/happy_things/new.html.erb
<%= stylesheet_link_tag "happy_things/new/new", :media => "all" %>

<% content_for :menubar do %>
  <%= link_to '最近のHAPPYを見る', happy_things_path %>
<% end %>
<% content_for :pagetitle do %>HAPPY登録<% end %>

<%= form_with(model: @happy_thing, local: true) do |form| %>
  <!--DB登録エラーがある場合-->
  <% if @happy_thing.errors.any? %>
    <div id="error_explanation">
      <ul>
      <!--エラーメッセージをリスト表示-->
      <% @happy_thing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

<div class="contents">
  <p>今日はどんないいことがありましたか？</p>
  <%= form_with(model: @happy_thing, local: true) do |form| %>
    <div class="field">
        <%= form.text_area :happy_things, id: :happy_thing_happy_things, :size => "35x5", :maxlength => "50" %>
    </div>
    <%= submit_tag "貯金する!" ,name: "entry_button"%>
  <% end %>
</div>

app/views/happy_things/show.html.erb
<%= stylesheet_link_tag "happy_things/show/show", :media => "all" %>

<% content_for :menubar do %>
  <%= link_to 'HAPPY一覧へ', happy_things_path %>
<% end %>

<div class="contents">
  <p>はっぴーを貯金しました！</p>
  <p>
    <%= @happy_thing.happy_things %>
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<%= stylesheet_link_tag "application", :media => "all" %>

  <head>
    <title>HappyBankApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="bottonframe">
        <%= yield :menubar %>
      </div>
      <h1 class="title">HAPPY BANK</h1>
    </header>
    <div class="wrap">
      <h2 class="pagetitle"><%= yield :pagetitle %></h1>
      <%= yield %>
    </div>
  </body>
</html>

app/views/login/login.html.erb
<h1>Login#login</h1>
<p>Find me in app/views/login/login.html.erb</p>

app/views/login/new_user.html.erb
<%= stylesheet_link_tag "new/new", :media => "all" %>

<%= form_with(model: @happy_thing, local: true) do |form| %>
  <!--DB登録エラーがある場合-->
  <% if @happy_thing.errors.any? %>
    <div id="error_explanation">
      <ul>
      <!--エラーメッセージをリスト表示-->
      <% @happy_thing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

<div class="contents">
  <%= form_for(@user) do |form| %>
    <p>ログインIDを入力してください</p>
    <div class="field">
        <%= form.text_field :user_id%>
    </div>
    <p>パスワードを入力してください</p>
    <div class="field">
        <%= form.text_field :user_password%>
        <p>確認用</p>
        <%= form.text_field :user_password_second%>
    </div>
    <%= form.submit "登録する" ,name: "entry_button"%>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.user_id %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= stylesheet_link_tag "users/new/new", :media => "all" %>

<% content_for :pagetitle do %>ユーザー登録<% end %>

<%= form_with(model: @user, local: true) do |form| %>
  <!--DB登録エラーがある場合-->
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <ul>
      <!--エラーメッセージをリスト表示-->
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="contents">
    <div class="field">
     <%= form.label :user_id, "ユーザーID" %>
     <%= form.text_field :user_id, id: :user_user_id, :size => "35x5", :maxlength => "10" %>
    </div>

    <div class="field">
     <%= form.label :password_digest, "パスワード" %>
     <%= form.password_field :password_digest, id: :user_password_digest, :size => "35x5", :maxlength => "10" %>
    </div>
  
    <div class="field">
     <%= form.label :password_confirmation, "パスワード(確認用)" %>
     <%= form.password_field :password_confirmation, id: :user_password_confirmation, :size => "35x5", :maxlength => "10" %>
    </div>

    <div class="actions">
     <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user.user_id %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>